name: Build Master
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    strategy:
      max-parallel: 2
      matrix:
        java:
          - '1.8'
          - '11.0.5'
        os:
          - ubuntu-latest
          - macos-latest
        exclude:
          - os: macos-latest
            java: '1.8'
    runs-on: ${{ matrix.os }}
    steps:
      - name: Fetch Sources
        uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Build
        run: |
          ./gradlew -S -Pskip.signing assemble
          ./gradlew -S -Pskip.signing check
