name: Build Master
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    strategy:
      max-parallel: 2
      matrix:
        java:
          - '8'
          - '11'
        os:
          - ubuntu-latest
          - macos-latest
        exclude:
          - os: macos-latest
            java: '8'
    runs-on: ${{ matrix.os }}
    steps:
      - name: Fetch Sources
        uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java }}
      - name: Build
        run: |
          ./gradlew -S -Pskip.signing assemble
          ./gradlew -S -Pskip.signing check
