name: Build Main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    strategy:
      max-parallel: 8
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        java:
          - 11
          - 17
          - 21
        jrubyVersion:
          - 9.4.13.0
          - 10.0.0.1
        exclude:
          - java: 11
            jrubyVersion: 10.0.0.1
          - java: 17
            jrubyVersion: 10.0.0.1
    runs-on: ${{ matrix.os }}
    steps:
      - name: Fetch Sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
      - name: Build & Test
        run: |
          ./gradlew -S -PjrubyVersion=${{ matrix.jRubyVersion }} -Pskip.signing tasks
  build-windows:
    name: Build
    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        os:
          - windows-latest
        java:
          - 11
          - 17
          - 21
        jrubyVersion:
          - 9.4.13.0
          - 10.0.0.1
        exclude:
          - java: 11
            jrubyVersion: 10.0.0.1
          - java: 17
            jrubyVersion: 10.0.0.1
    runs-on: ${{ matrix.os }}
    steps:
      - name: Fetch Sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
      - name: Build & Test
        shell: cmd
        run: |
          gradlew.bat -S -PjrubyVersion=${{ matrix.jRubyVersion }} -Pskip.signing assemble check
