name: Upstream Build
on: workflow_dispatch

jobs:
  build:
    name: Test Upstream
    strategy:
      max-parallel: 2
      matrix:
        java:
          - '21'
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Sources
        uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
      - name: Upstream Build
        run: |
          ./test-asciidoctor-upstream.sh


