name: Upstream Build
on:
  # keep this separate from nightly build, as GitHub will disable scheduled builds after 30 days
  # without a change (and won't enable them automatically, for example on pushed changes or pull requests)
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    strategy:
      max-parallel: 2
      matrix:
        java:
          - '11'
          - '17'
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Sources
        uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
      - name: Upstream Build
        run: |
          ./test-asciidoctor-upstream.sh


