name: Upstream Build
on:
  # keep this separate from nightly build, as GitHub will disable scheduled builds after 30 days
  # without a change (and won't enable them automatically, for example on pushed changes or pull requests)
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Sources
        uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '1.8'
      - name: Upstream Build
        run: |
          ./test-asciidoctor-upstream.sh


